project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "Andrew S. Rosenberg"
  description: "Associate Professor of Political Science, University of Florida"
  site-url: "https://www.andrew-rosenberg.com"
  open-graph: true
  twitter-card: true
  navbar:
    pinned: true
    background: white
    foreground: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        menu:
          - text: "Publications"
            href: publications.qmd
          - text: "Working Papers"
            href: working-papers.qmd
      - text: "Books"
        menu:
          - text: "Undesirable Immigrants"
            href: books/undesirable.qmd
          - text: "Hierarchies of Worth"
            href: books/hierarchies.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: assets/asr-cv.pdf
      - text: "Contact"
        href: contact.qmd
  page-footer:
    center: "© 2026 Andrew S. Rosenberg. All Rights Reserved."

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: false
    fontsize: 1.0rem
    linkcolor: "#1d6fa5"
    grid:
      body-width: 960px
      sidebar-width: 0px
      margin-width: 0px
