---
title: "Publications"
---

## Peer-Reviewed Articles

**Rosenberg, Andrew S.** and Nazli Avdan. 2024. "Assessing Border Walls' Varied
Impacts on Terrorist Group Diffusion." *Conflict Management and Peace Science*.
[[DOI]](https://doi.org/10.1177/07388942241270927)

**Rosenberg, Andrew S.** 2024. "Race and Systemic Crises in International
Politics: An Agenda for Pluralistic Scholarship." *Review of International
Studies* 50(3): 457–475. [[DOI]](https://doi.org/10.1017/S0260210523000761)

Avdan, Nazli, **Andrew S. Rosenberg**, and Christopher Gelpi. 2023. "Where
There's a Will, There's a Way: Border Walls and Refugees." *Journal of Peace
Research*. [[DOI]](https://doi.org/10.1177/00223433231200918)

**Rosenberg, Andrew S.** 2023. "Racial Discrimination in International Visa
Policies." *International Studies Quarterly* 67(2): sqad032.
[[DOI]](https://doi.org/10.1093/isq/sqad032)

**Rosenberg, Andrew S.** 2022. "Agents, Structures, and the Moral Basis of
Deportability." *Security Dialogue* 54(6): 602–619.
[[DOI]](https://doi.org/10.1177/09670106221113183)

Pierskalla, Jan H., Adam Lauretig, **Andrew S. Rosenberg**, and Audrey Sacks.
2020. "Democratization and Representative Bureaucracy — An Analysis of
Promotion Patterns in Indonesia's Civil Service, 1980–2015." *American Journal
of Political Science* 65(2): 261–277.
[[DOI]](https://doi.org/10.1111/ajps.12536)

**Rosenberg, Andrew S.** 2019. "Measuring Racial Bias in International
Migration Flows." *International Studies Quarterly* 63(4): 837–845.
[[DOI]](https://doi.org/10.1093/isq/sqz039)

**Rosenberg, Andrew S.**, Austin J. Knuppe, and Bear F. Braumoeller. 2017.
"Unifying the Study of Asymmetric Hypotheses." *Political Analysis* 25(3):
381–401. [[DOI]](https://doi.org/10.1017/pan.2017.16)
